`method <- control$method
hessian <- control$hessian
ocontrol <- control
control$method <- control$hessian <- control$EM <- control$start <- NULL
fit <- optim(fn = loglikfun, gr = gradfun,
   par = c(start$count, start$zero, if(dist == "negbin") log(start$theta) else NULL),
   method = method, hessian = hessian, control = control)
if(fit$convergence > 0) warning("optimization failed to converge")`

`## coefficients and covariances
coefc <- fit$par[1:kx]
names(coefc) <- names(start$count) <- colnames(X)
coefz <- fit$par[(kx+1):(kx+kz)]
names(coefz) <- names(start$zero) <- colnames(Z)`

`vc <- -solve(as.matrix(fit$hessian))
if(dist == "negbin") {
   np <- kx + kz + 1
   theta <- as.vector(exp(fit$par[np]))
   SE.logtheta <- as.vector(sqrt(diag(vc)[np]))
   vc <- vc[-np, -np, drop = FALSE]
 } else {
    theta <- NULL
    SE.logtheta <- NULL
  }
  colnames(vc) <- rownames(vc) <- c(paste("count", colnames(X), sep = "_"),
                                    paste("zero",  colnames(Z), sep = "_"))`

`## fitted and residuals
mu <- exp(X %*% coefc + offsetx)[,1]
phi <- linkinv(Z %*% coefz + offsetz)[,1]
Yhat <- (1-phi) * mu
res <- sqrt(weights) * (Y - Yhat)`

In [152]:
fit = sp.optimize.minimize(loglikfun, args=(-1.0,), x0 = np.hstack((start['count'].values,start['zero'].values)),\
            method='BFGS', jac=gradfun, options={'disp': False, 'maxiter': 10000}, tol = reltol)

In [119]:
sm.Logit(1)

TypeError: __init__() missing 1 required positional argument: 'exog'

In [153]:
## coefficients and covariances
coefc = pd.Series(data = fit.x[0:kx], index = X.columns.values)
coefz = pd.Series(data = fit.x[kx:kx+kz], index = Z.columns.values)
vc = pd.DataFrame(data = -fit.hess_inv, index = np.append(X.columns.values, Z.columns.values),\
                 columns = np.append(X.columns.values, Z.columns.values))

In [162]:
## fitted and residuals
mu = np.exp(np.dot(X,coefc)+offsetx)
phi = linkinv(np.dot(Z,coefz)+offsetz)
Yhat = (1-phi) * mu
res = np.sqrt(weights) * (Y - Yhat)

In [155]:
vc

Intercept  health[T.excellent]  health[T.poor]  \
Intercept            -0.000601             0.000032        0.000067   
health[T.excellent]   0.000032            -0.000988       -0.000022   
health[T.poor]        0.000067            -0.000022       -0.000314   
gender[T.male]        0.000044             0.000004       -0.000002   
privins[T.yes]        0.000145            -0.000001       -0.000027   
hosp                  0.000002            -0.000005        0.000017   
numchron              0.000042            -0.000015        0.000027   
school                0.000031             0.000004       -0.000004   
Intercept            -0.000038             0.000010        0.000006   
health[T.excellent]  -0.000022            -0.000364       -0.000008   
health[T.poor]        0.000031            -0.000010       -0.000015   

                     gender[T.male]  privins[T.yes]          hosp  \
Intercept              4.388028e-05        0.000145  2.371374e-06   
health[T.excellent]    3.741862e-06       -0.000001 -5.108776e-06   
health[T.poor]        -1.730619e-06       -0.000027  1.688542e-05   
gender[T.male]        -1.719386e-04        0.000013  2.576869e-06   
privins[T.yes]         1.310409e-05       -0.000300  5.109038e-06   
hosp                   2.576869e-06        0.000005 -3.671321e-05   
numchron               1.357182e-06       -0.000003  5.184157e-06   
school                 5.865812e-07        0.000010 -1.852801e-07   
Intercept             -6.309347e-06        0.000011  1.004918e-06   
health[T.excellent]   -6.082406e-06        0.000003 -3.601112e-07   
health[T.poor]         4.163475e-06       -0.000009  7.533150e-08   

                         numchron        school  Intercept  \
Intercept            4.194402e-05  3.082563e-05  -0.000038   
health[T.excellent] -1.452878e-05  4.385886e-06   0.000010   
health[T.poor]       2.658064e-05 -3.993200e-06   0.000006   
gender[T.male]       1.357182e-06  5.865812e-07  -0.000006   
privins[T.yes]      -2.979811e-06  9.675533e-06   0.000011   
hosp                 5.184157e-06 -1.852801e-07   0.000001   
numchron            -2.243578e-05 -2.640444e-07   0.000005   
school              -2.640444e-07 -3.553572e-06   0.000001   
Intercept            4.710941e-06  1.274083e-06  -0.002314   
health[T.excellent]  2.004751e-06  2.499764e-06   0.002312   
health[T.poor]      -3.333073e-06 -9.662352e-07   0.002311   

                     health[T.excellent]  health[T.poor]  
Intercept                  -2.200580e-05    3.105405e-05  
health[T.excellent]        -3.643345e-04   -9.819426e-06  
health[T.poor]             -7.745983e-06   -1.517821e-05  
gender[T.male]             -6.082406e-06    4.163475e-06  
privins[T.yes]              3.450431e-06   -8.854319e-06  
hosp                       -3.601112e-07    7.533150e-08  
numchron                    2.004751e-06   -3.333073e-06  
school                      2.499764e-06   -9.662352e-07  
Intercept                   2.311685e-03    2.311389e-03  
health[T.excellent]        -2.116091e-02   -2.306497e-03  
health[T.poor]             -2.306497e-03   -2.147779e-02

In [156]:
mu

array([  6.66911641,   6.56389032,  15.3987347 , ...,  10.22539213,
         5.5522598 ,   2.77613353])

In [163]:
phi

array([ 0.15012237,  0.15012237,  0.10594971, ...,  0.15012237,
        0.15012237,  0.22119154])

In [164]:
Yhat

array([  5.66793287,   5.57850358,  13.76724315, ...,   8.69033207,
         4.71874142,   2.16207629])

In [165]:
res

array([ -0.66793287,  -4.57850358,  -0.76724315, ...,   1.30966793,
        11.28125858,  -2.16207629])

In [160]:
coefc

Intercept              1.393672
health[T.excellent]   -0.307754
health[T.poor]         0.254201
gender[T.male]        -0.064859
privins[T.yes]         0.085441
hosp                   0.159127
numchron               0.103280
school                 0.019591
dtype: float64

In [161]:
coefz

Intercept             -1.733642
health[T.excellent]    0.474906
health[T.poor]        -0.399156
dtype: float64

In [104]:
np.exp(np.dot(X,coefc)+offsetx).shape

(4406,)

In [95]:
y = np.append(X.columns.values, Z.columns.values)

In [97]:
X.columns.values

array(['Intercept', 'health[T.excellent]', 'health[T.poor]',
       'gender[T.male]', 'privins[T.yes]', 'hosp', 'numchron', 'school'], dtype=object)

In [58]:
(fit.hess_inv).shape

(11, 11)

pandas.core.indexes.base.Index

In [56]:
np.hstack((start['count'].values,start['zero'].values)).shape

(11,)

In [30]:
## coefficients and covariances
coefc = fit.x[0:kx]
#names(coefc) <- names(start$count) <- colnames(X)
#coefz <- fit$par[(kx+1):(kx+kz)]
#names(coefz) <- names(start$zero) <- colnames(Z)

In [36]:
type(start['count'])

pandas.core.series.Series

In [151]:
import numpy as np
import pandas as pd
import patsy
df = pd.read_csv('DebTrivedi.csv',index_col = [0])
sel = np.array([1, 6, 7, 8, 13, 15, 18])-1
df = df.iloc[:,sel]
# produce design matrices from R-style formula
X_formula = 'ofp ~ hosp + health + numchron + gender + school + privins'
y, X = patsy.dmatrices(X_formula, df, return_type='dataframe')
Z_formula = 'ofp ~ health'
Z = patsy.dmatrices(Z_formula, df, return_type='dataframe')[1]

## convenience variables
Y = np.squeeze(y.values)
n = len(Y)
kx = X.shape[1] # Number of columns in X
kz = Z.shape[1]
Y0 = Y <= 0
Y1 = Y > 0

offsetx = np.zeros(n)
offsetz = np.zeros(n)
weights = np.ones(n)

import statsmodels.api as sm
import scipy as sp
linkinv = sp.special.expit
linkobj = sp.special.logit

def ziPoisson(parms, sign = 1.0):
    ## count mean
    mu = np.exp(np.dot(X,parms[np.arange(kx)]) + offsetx)
    ## binary mean
    phi = linkinv(np.dot(Z, parms[np.arange(kx,kx+kz)]) + offsetz)
    ## log-likelihood for y = 0 and y >= 1
    loglik0 = np.log( phi + np.exp( np.log(1-phi) - mu ) ) ## -mu = dpois(0, lambda = mu, log = TRUE)
    loglik1 = np.log(1-phi) + sp.stats.poisson.logpmf(Y, mu)
    ## collect and return
    loglik = np.dot(weights[Y0],loglik0[Y0])+np.dot(weights[Y1],loglik1[Y1])
    return sign*loglik

def gradPoisson(parms, sign = 1.0):
    ## count mean
    eta = np.dot(X,parms[np.arange(kx)]) + offsetx
    mu = np.exp(eta)
    ## binary mean
    etaz = np.dot(Z, parms[np.arange(kx,kx+kz)]) + offsetz
    muz = linkinv(etaz)
    ## densities at 0
    clogdens0 = -mu
    dens0 = muz*(1-Y1.astype(float)) + np.exp(np.log(1 - muz) + clogdens0)
    ## working residuals  
    wres_count = np.where(Y1,Y-mu,-np.exp(-np.log(dens0) + 
                                          np.log(1 - muz) + clogdens0 + np.log(mu))) 
    link_etaz = np.exp(etaz)/(1+np.exp(etaz))**2
    wres_zero  = np.where(Y1,-1/(1-muz) * link_etaz, \
                          (link_etaz - np.exp(clogdens0) * link_etaz)/dens0)
    
    
    return sign*(np.hstack((np.expand_dims(wres_count*weights,axis=1)*X, \
                np.expand_dims(wres_zero*weights,axis=1)*Z))).sum(axis=0)

loglikfun = ziPoisson
gradfun = gradPoisson
reltol =  (np.finfo(float).eps)**(1/1.6)

model_count = sm.GLM(endog = Y, exog = X, family = sm.families.Poisson(),\
                                  offset = offsetx , freq_weights = weights).fit()
model_zero = sm.GLM(Y0.astype(int), exog = Z, family=sm.families.Binomial(), \
                   offset = offsetz , freq_weights = weights).fit()
start = {'zero':model_zero.params, 'count':model_count.params}

mui = model_count.predict()
probi = model_zero.predict()
probi = probi/(probi + (1-probi)*sp.stats.poisson.pmf(0, mui))
probi[Y1] = 0

ll_new = loglikfun(np.hstack((start['count'].values,start['zero'].values)))
ll_old = 2 * ll_new

while np.absolute((ll_old - ll_new)/ll_old) > reltol :
    ll_old = ll_new
    model_count = poisson_mod = sm.GLM(endog = Y, exog = X, family = sm.families.Poisson(),\
                                  offset = offsetx , freq_weights = weights*(1-probi), \
                                      start_params = start['count']).fit()
    model_zero = sm.GLM(probi, exog = Z, family=sm.families.Binomial(),\
                        offset = offsetz, freq_weights = weights, \
                        start_params = start['zero']).fit()
    start = {'zero':model_zero.params, 'count':model_count.params}

    mui = model_count.predict()
    probi = model_zero.predict()
    probi = probi/(probi + (1-probi)*sp.stats.poisson.pmf(0, mui))
    probi[Y1] = 0

    ll_new = loglikfun(np.hstack((start['count'].values,start['zero'].values)))

In [167]:
sm.GLM(endog = Y, exog = X, family = sm.families.Poisson(),\
                                  offset = offsetx , freq_weights = weights).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                 4406
Model:                            GLM   Df Residuals:                     4398
Model Family:                 Poisson   Df Model:                            7
Link Function:                    log   Scale:                             1.0
Method:                          IRLS   Log-Likelihood:                -17972.
Date:                Sat, 31 Mar 2018   Deviance:                       23168.
Time:                        18:32:28   Pearson chi2:                 2.95e+04
No. Iterations:                     5                                         
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               1.0289      0.024     43.257      0.000       0.982       1.075
health[T.excellent]    -0.3620      0.030    -11.945      0.000      -0.421      -0.303
health[T.poor]          0.2483      0.018     13.915      0.000       0.213       0.283
gender[T.male]         -0.1123      0.013     -8.677      0.000      -0.138      -0.087
privins[T.yes]          0.2017      0.017     11.962      0.000       0.169       0.235
hosp                    0.1648      0.006     27.478      0.000       0.153       0.177
numchron                0.1466      0.005     32.019      0.000       0.138       0.156
school                  0.0261      0.002     14.182      0.000       0.023       0.030
=======================================================================================
"""

In [150]:
start['count']

Intercept              1.393671
health[T.excellent]   -0.307757
health[T.poor]         0.254201
gender[T.male]        -0.064859
privins[T.yes]         0.085441
hosp                   0.159127
numchron               0.103280
school                 0.019591
dtype: float64

In [171]:
from statsmodels.genmod.generalized_estimating_equations import GEE

In [172]:
?GEE